security:

    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # users:
        #     pattern : api/users
        #     stateless : true
        #     jwt: ~
        #     methods: [GET, POST, PUT, PATCH, DELETE]
        # api:
        #     pattern:   ^/api
        #     stateless: true
        #     entry_point: jwt

        refresh_token:
            pattern:   ^/api/token/refresh
            stateless: true
            refresh_jwt: ~

        exercises:
            pattern : api/exercises
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        fitnesses:
            pattern : api/fitnesses
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        gainages:
            pattern : api/gainages
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        musculations:
            pattern : api/musculations
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        titresfits:
            pattern : api/titresfits
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        titresgainages:
            pattern : api/titresgainages
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        titresmuscus:
            pattern : api/titresmuscus
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        trainings:
            pattern : api/trainings
            stateless : true
            methods: [GET, POST, PUT, PATCH, DELETE]
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider


# Easy way to control access for large sections of your site
# Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        # - { path: ^/api/persons, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        # - { path: ^/api,       roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/exercises, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/fitnesses, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/gainages, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/musculations, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/titresfits, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/titresgainages, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/titresmuscus, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }
        - { path: ^/api/trainings, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, PATCH, DELETE] }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
